apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: insideinfo-web-prod-updater
  namespace: argocd
spec:
  commonUpdateSettings:
    pullSecret: pullsecret:argocd/gitlab-registry-secret
    updateStrategy: newest-build
    forceUpdate: true
    allowTags: "regexp:^prod-[0-9]{8}-[0-9]{4}$"
  writeBackConfig:
    method: git
    gitConfig:
      branch: main
      writeBackTarget: "helmvalues:./values/prod/inside-web-values.yaml"
  applicationRefs:
    - namePattern: "insideinfo-web-prod"
      images:
        - alias: web
          imageName: gitlab.insideinfo.co.kr:5005/ax-2/insideinfo-web/insideinfo-web
          manifestTargets:
            helm:
              name: image.repository
              tag: image.tag
