apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: insideinfo-api-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://gitlab.insideinfo.co.kr/ax-2/insideinfo-gitops.git
    targetRevision: main
    path: apps/insideinfo-api/helm
    helm:
      valueFiles:
        - values/prod/inside-api-values.yaml
        - secrets://values/prod/secret-values.enc.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: insideinfo
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
