apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "insideinfo-api.fullname" . }}-properties
  labels:
    {{- include "insideinfo-api.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.configmap.data.properties | nindent 2 }}
