{{- if .Values.httproute.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "insideinfo-api.fullname" . }}
  labels:
    {{- include "insideinfo-api.labels" . | nindent 4 }}
spec:
  parentRefs:
  - name: {{ .Values.httproute.gatewayName }}
    namespace: {{ .Values.httproute.gatewayNamespace }}
  hostnames:
    {{- range .Values.httproute.hostnames }}
  - {{ . | quote }}
    {{- end }}
  rules:
  - backendRefs:
    - name: {{ include "insideinfo-api.fullname" . }}
      port: {{ .Values.service.port }}
{{- end }}
