{{- if .Values.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "insideinfo-api.fullname" . }}-config
  labels:
    {{- include "insideinfo-api.labels" . | nindent 4 }}
stringData:
  {{- toYaml .Values.secret.data.config | nindent 2 }}
{{- end }}
