secret:
    data:
        config:
            application-secret.yml: ENC[AES256_GCM,data:IE4EIdjlQ8t1UhodfnyKoE8kkZWYthhntvujG+99pGkdEuaV+OmyTS1WFQgDRzfFgNbTc9Z3MEukzwpRkzY3YRiZEoxua3Krg7AkVo+r6Q9eQgbf2GhT8PBmXiUGD4TGNLPdv9cDNT8PEcIm/XPDcfKk3EZhjsj55Na3ioyqUz3tLmW5g0In1JdFXgpJSga1xu7GAL57UVD5/r7sOFDw0xVyYwco4Cx6ndw371Q4LDf39b/wbMi362cCo/+EWQyrUTJjGCuaJYHBvOgRyzRERodv9pmF,iv:S0I1IEHAR5gBUfs7tIKcFQ+pGbSV4BoMgSp0B39mO6U=,tag:EQ/4DX/hYheG4URxCczffA==,type:str]
sops:
    age:
        - recipient: age14mzxcffuanlxdwvvv47gcmn9kh6gy8d3yn3r6u3gya5ddt4xr3vqxc47kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5eFBsNUIybGJOQ1d5blFy
            dWhRRUZybkdPTlJaV1NtMTYrVUpXL205Z0NjClZsZHpWK3JmeGZvNndoQWpiaUNJ
            VWdRc0dyM2EzZWdQaGVXeFg2MFdlT2sKLS0tIGJ2cm10VjJxQlhadEVDajV6cE9O
            aTdFU1RYMWRhTllDQWxaZjByVWpWc2cKCCiBMCvc/sJzM4OlP8UfrMCbvq4lGe6g
            xAkPc7pyY79Mnq4HPHIO0faXXZ82upeJBunV47NNF5ZVEdLHKQI+TA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-16T04:16:27Z"
    mac: ENC[AES256_GCM,data:lEW5FvD+S9dP3gqdUU3krMDFDWo27syEKwjj0A9+4NT1Yk4VJeBeF/Kf00WCWw980EenvkO9du12DmWpx2xyk98yewcC32eXDKYd/Eqmnmy/BlfHl294zCcQpI/8z2lYXn7Is7ae05Vhc8i65qmDpkXYxIstEAWyP/X+PUGBI50=,iv:2grofLk8If1TRv4ze46FeWeZgI8rs5PSS34x2w8R6sI=,tag:/oyFLnG9uDjztnUbIegSiw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
