secret:
    data:
        config:
            application-secret.yml: ENC[AES256_GCM,data:Uld8oLs40C0KMQlDjfMvYwF2sPtZz2YmA1w6UDHmNzviY2+q8opfH/m1WkgqWkvWqZOFN/BagCvHgey3kAHio7sJpfi+rC1teuQzmigM4HoAYa/jKWkGbvFGlTyD4f+i3LnIhCld+sdwtKIfdmbDlMtBqWL1b0ldptma34KcOdnoyV56YsZ4874OGPNSdVGEn4B7pq2NbKgDOvTtKlfRwGaiKr+8YA4AxNCa4r0Otyf9Y3t058uZe6UQRF1Liu6a6eWqwPYW/q3FaZRWt0qPWlbnIahZWg==,iv:slaNJrvq0phZqNwUoEn7U3KrGFZbQssBn0P5e1PhcAk=,tag:SKbA7ZVOn+wrkcyrfIVv5g==,type:str]
sops:
    age:
        - recipient: age14mzxcffuanlxdwvvv47gcmn9kh6gy8d3yn3r6u3gya5ddt4xr3vqxc47kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyMHRuVERVYnlUV25mbjVm
            Zi9aVk9zMjcwY0RZaDF5RjlmRDVKdERydzI0Ci8wZWljZG01R3lCMGp0dnppdTdX
            V3gvWkpIVW9RZFoxL3BsMittekROZkEKLS0tIGhLVTFZajdkMFpOaUxCT2kwd01q
            UzhUZ25UMzdYbmlRQk9hclMzd3dTQTgKdP0qPd6/AzAjS7ouAZ0fS/Ji1BPQaldt
            IDAvlclihZT5KhTa27EYpEMdFt0IZDN+JIb8edjxNKC6bm/NWWHPPw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-16T04:16:27Z"
    mac: ENC[AES256_GCM,data:lsVogw3vWzv5HK+TajFlDosKH6F9mRfN/6TfPm42A2nFECBC4aOKBHprIxLwLOJ1Gm4oaoHnVwiD1+aHDT6weucUNmTn5hYNhHut3K2P8HxZeeHfJD8y1NCmpfLPv9E1TLz7yVOrQJFU/FHFpUZlv9OgnQ6ziYTwXTJb8PU421M=,iv:87rQVa/loAUd5wnPiT6R0R8zOs8UV+wktLfY65ZJcRw=,tag:VLxSLwb19puPdO1nsw/yqA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
